# Generated by Django 5.1.4 on 2024-12-17 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userdata_appointbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointbooking',
            name='user',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='users.userdata'),
            preserve_default=False,
        ),
    ]
